#!/bin/bash

function hash() {
    printf "%s: " "$1" 1>&2
    read -s password
    echo 1>&2
    filtered=`echo "$password" | grep -Po '[\x00-\x7f]*'`
    [ "$password" == "$filtered" ] || {
        echo "Only non-unicode characters are allowed." 1>&2
        exit 1
    }
    printf "%s" "$password" | sha512sum | grep -Po [0-9a-fA-F]{128}
}

hash1=`hash "Enter password"`
hash2=`hash "Retype password"`

if [ "$hash1" == "$hash2" ]; then
    echo "password $hash1"
    exit 0
else
    echo "Passwords do not match." 1>&2
    exit 1
fi
